"""
Database backup script for Railway MySQL to AWS S3.

Usage:
    python backup_db.py                    # Manual backup
    python backup_db.py --on-completion    # Called after session completes

Backups are stored in S3 with timestamps:
    s3://flight-app-db-backups/backup_2024-02-11_143022.sql.gz
"""

import os
import subprocess
import gzip
import boto3
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

# AWS S3 Configuration (set via environment variables or .env file)
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY', '')
S3_BUCKET = os.getenv('S3_BACKUP_BUCKET', 'flight-app-db-backups')
S3_REGION = os.getenv('S3_REGION', 'us-east-1')

# MySQL Configuration (set via environment variables or .env file)
MYSQL_HOST = os.getenv('MYSQL_HOST', '')
MYSQL_PORT = os.getenv('MYSQL_PORT', '3306')
MYSQL_DATABASE = os.getenv('MYSQL_DATABASE', '')
MYSQL_USER = os.getenv('MYSQL_USER', '')
MYSQL_PASSWORD = os.getenv('MYSQL_PASSWORD', '')


def create_mysql_dump():
    """Create a MySQL dump using mysqldump or Python fallback."""
    timestamp = datetime.utcnow().strftime('%Y-%m-%d_%H%M%S')
    dump_filename = f'backup_{timestamp}.sql'

    try:
        # Try using mysqldump if available
        cmd = [
            'mysqldump',
            f'--host={MYSQL_HOST}',
            f'--port={MYSQL_PORT}',
            f'--user={MYSQL_USER}',
            f'--password={MYSQL_PASSWORD}',
            '--single-transaction',
            '--routines',
            '--triggers',
            MYSQL_DATABASE
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)

        if result.returncode == 0:
            return dump_filename, result.stdout
        else:
            print(f"mysqldump failed: {result.stderr}")
            # Fall back to Python-based export
            return create_python_dump(dump_filename)

    except FileNotFoundError:
        print("mysqldump not found, using Python-based export")
        return create_python_dump(dump_filename)


def create_python_dump(dump_filename):
    """Create a database dump using Python/SQLAlchemy."""
    import pymysql

    conn = pymysql.connect(
        host=MYSQL_HOST,
        port=int(MYSQL_PORT),
        user=MYSQL_USER,
        password=MYSQL_PASSWORD,
        database=MYSQL_DATABASE,
        connect_timeout=30
    )

    cursor = conn.cursor()
    dump_content = []

    # Header
    dump_content.append(f"-- MySQL dump generated by backup_db.py")
    dump_content.append(f"-- Generated at: {datetime.utcnow().isoformat()}")
    dump_content.append(f"-- Database: {MYSQL_DATABASE}")
    dump_content.append("")
    dump_content.append("SET FOREIGN_KEY_CHECKS=0;")
    dump_content.append("")

    # Get all tables
    cursor.execute("SHOW TABLES")
    tables = [row[0] for row in cursor.fetchall()]

    for table in tables:
        # Get CREATE TABLE statement
        cursor.execute(f"SHOW CREATE TABLE `{table}`")
        create_stmt = cursor.fetchone()[1]
        dump_content.append(f"-- Table: {table}")
        dump_content.append(f"DROP TABLE IF EXISTS `{table}`;")
        dump_content.append(f"{create_stmt};")
        dump_content.append("")

        # Get data
        cursor.execute(f"SELECT * FROM `{table}`")
        rows = cursor.fetchall()

        if rows:
            # Get column names
            cursor.execute(f"DESCRIBE `{table}`")
            columns = [col[0] for col in cursor.fetchall()]

            for row in rows:
                values = []
                for val in row:
                    if val is None:
                        values.append('NULL')
                    elif isinstance(val, (int, float)):
                        values.append(str(val))
                    elif isinstance(val, bytes):
                        values.append(f"X'{val.hex()}'")
                    else:
                        escaped = str(val).replace("\\", "\\\\").replace("'", "\\'")
                        values.append(f"'{escaped}'")

                dump_content.append(f"INSERT INTO `{table}` VALUES ({', '.join(values)});")

            dump_content.append("")

    dump_content.append("SET FOREIGN_KEY_CHECKS=1;")

    conn.close()

    return dump_filename, '\n'.join(dump_content)


def upload_to_s3(filename, content):
    """Compress and upload the dump to S3."""
    # Compress content
    compressed = gzip.compress(content.encode('utf-8'))
    gzip_filename = f"{filename}.gz"

    # Initialize S3 client
    s3_client = boto3.client(
        's3',
        aws_access_key_id=AWS_ACCESS_KEY_ID,
        aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
        region_name=S3_REGION
    )

    # Upload to S3
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=gzip_filename,
        Body=compressed,
        ContentType='application/gzip'
    )

    return gzip_filename


def cleanup_old_backups(keep_days=30):
    """Remove backups older than keep_days."""
    from datetime import timedelta

    s3_client = boto3.client(
        's3',
        aws_access_key_id=AWS_ACCESS_KEY_ID,
        aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
        region_name=S3_REGION
    )

    cutoff = datetime.utcnow() - timedelta(days=keep_days)

    response = s3_client.list_objects_v2(Bucket=S3_BUCKET)

    if 'Contents' not in response:
        return 0

    deleted = 0
    for obj in response['Contents']:
        if obj['LastModified'].replace(tzinfo=None) < cutoff:
            s3_client.delete_object(Bucket=S3_BUCKET, Key=obj['Key'])
            deleted += 1
            print(f"  Deleted old backup: {obj['Key']}")

    return deleted


def run_backup(on_completion=False):
    """Run the backup process."""
    print("=" * 50)
    print("Database Backup")
    print("=" * 50)

    try:
        # Create dump
        print("\n1. Creating database dump...")
        filename, content = create_mysql_dump()
        size_kb = len(content) / 1024
        print(f"   Dump created: {size_kb:.1f} KB")

        # Upload to S3
        print("\n2. Uploading to S3...")
        gzip_filename = upload_to_s3(filename, content)
        print(f"   Uploaded: s3://{S3_BUCKET}/{gzip_filename}")

        # Cleanup old backups (keep 30 days)
        print("\n3. Cleaning up old backups...")
        deleted = cleanup_old_backups(30)
        print(f"   Deleted {deleted} old backups")

        print("\n" + "=" * 50)
        print("Backup complete!")
        print("=" * 50)

        return True

    except Exception as e:
        print(f"\n ERROR: Backup failed: {e}")
        return False


if __name__ == "__main__":
    import sys

    on_completion = '--on-completion' in sys.argv
    success = run_backup(on_completion=on_completion)
    sys.exit(0 if success else 1)
